In [1]:
import numpy as np
import matplotlib as plt
%matplotlib inline

In [23]:
r = np.random.randint(16,size=8)

In [20]:
r

[4, 2, 0, 2, 7, 4, 8, 5]

In [21]:
#help(np.random.randint)

In [24]:
np.mean(r)

5.75

In [25]:
r.sort()

In [26]:
r

array([ 1,  1,  4,  6,  7,  8,  9, 10])

In [27]:
np.median(r)

6.5

In [28]:
from statistics import mode

In [29]:
mode(r)

1

In [31]:
help(np.random.random_integers)

Help on built-in function random_integers:

random_integers(...) method of mtrand.RandomState instance
    random_integers(low, high=None, size=None)
    
    Random integers of type np.int between `low` and `high`, inclusive.
    
    Return random integers of type np.int from the "discrete uniform"
    distribution in the closed interval [`low`, `high`].  If `high` is
    None (the default), then results are from [1, `low`]. The np.int
    type translates to the C long type used by Python 2 for "short"
    integers and its precision is platform dependent.
    
    This function has been deprecated. Use randint instead.
    
    .. deprecated:: 1.11.0
    
    Parameters
    ----------
    low : int
        Lowest (signed) integer to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is the *highest* such
        integer).
    high : int, optional
        If provided, the largest (signed) integer to be drawn from the
        distribution (see ab

In [75]:
population = np.random.randint(10,99,118)


In [76]:
population.sort()

In [77]:
print(population)

[12 12 12 14 14 15 15 16 16 19 19 20 21 22 22 22 22 23 24 24 24 25 25 25
 25 25 26 27 27 29 30 30 31 32 33 34 35 36 36 37 37 37 38 39 40 40 45 46
 46 46 47 49 50 51 52 54 54 54 55 56 57 57 58 58 58 58 59 60 61 62 63 63
 65 65 65 65 65 65 66 66 67 69 69 69 70 70 72 73 73 73 74 74 74 74 74 75
 76 76 77 78 80 81 81 83 86 87 87 87 90 90 90 91 95 96 96 97 97 98]


In [78]:
np.mean(population)

52.516949152542374

In [79]:
np.median(population)

55.5

In [80]:
mode(population)

65

In [88]:
sample=np.random.choice(population,17)
sample

array([15, 74, 87, 70, 30, 97, 24, 77, 16, 30, 87, 50, 36, 46, 70, 75, 70])

In [92]:
print(np.mean(sample))
print(np.median(sample))
print(mode(sample))

56.11764705882353
70.0
70


In [97]:
sample1=np.random.choice(population,15)
sample2=np.random.choice(population,15)
sample3=np.random.choice(population,15)
sample4=np.random.choice(population,15)

In [98]:
l = [sample1,sample2,sample3,sample4]

In [99]:
l

[array([69, 27, 77, 36, 59, 15, 96, 90, 27, 69, 37, 57, 74, 46, 32]),
 array([16, 57, 16, 54, 70, 74, 46, 24, 58, 91, 81, 16, 62, 76, 87]),
 array([21, 46, 58, 76, 46, 65, 46, 76, 52, 72, 87, 58, 60, 77, 22]),
 array([78, 65, 58, 56, 32, 33, 37, 16, 30, 76, 22, 76, 63, 65, 36])]

In [106]:
for i in l:
    print(i)
    a=np.mean(i)
    b=np.median(i)
    print(a)
    print(b)
    #mode(i)

[69 27 77 36 59 15 96 90 27 69 37 57 74 46 32]
54.06666666666667
57.0
[16 57 16 54 70 74 46 24 58 91 81 16 62 76 87]
55.2
58.0
[21 46 58 76 46 65 46 76 52 72 87 58 60 77 22]
57.46666666666667
58.0
[78 65 58 56 32 33 37 16 30 76 22 76 63 65 36]
49.53333333333333
56.0


In [109]:
combine_sample=[]
for i in l:
    combine_sample.append(np.mean(i))

combine_sample

[54.06666666666667, 55.2, 57.46666666666667, 49.53333333333333]

In [112]:
num =np.random.randn(40)

In [113]:
num

array([ 1.35189969,  0.22456517,  2.19598252,  1.20738731,  0.69837117,
        0.08958075, -0.19154187,  0.99416863,  0.06035372, -2.97075664,
       -0.11955268, -0.47169125, -0.29642629, -1.66128995,  1.16227192,
       -0.15240389, -0.63765831,  0.57676458,  0.50369064,  0.96853774,
       -0.3823411 , -1.47947983,  0.54413881, -1.46311368, -1.80147208,
       -1.03752163,  0.88489633,  0.71592515,  1.50531716, -0.24247938,
        0.08226733,  0.64845356,  1.18709682, -0.54246092, -0.60611958,
        1.76420635,  2.24207292,  0.40957074,  0.39843437,  0.77456271])

In [114]:
range=max(num)-min(num)

In [115]:
range

5.212829563807034

In [119]:
Q1 = np.percentile(num,75)
Q2 = np.percentile(num,50)
Q3 = np.percentile(num,75)

In [122]:
Q=Q3-Q1

In [123]:
Q

0.0

In [126]:
np.var(population)

609.3005601838552

In [127]:
np.var(sample)

677.0449826989618